### ISSUE TITLE
Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by bean-point** [aimagelab/meshed-memory-transformer#12]
Epoch 0 - train:   0%|                                                                                                                                           | 0/11328 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 239, in <module>
    train_loss = train_xe(model, dataloader_train, optim, text_field)
  File "train.py", line 75, in train_xe
    for it, (detections, captions) in enumerate(dataloader):
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/meshed-memory-transformer-master/data/dataset.py", line 42, in __getitem__
    data.append(field.preprocess(getattr(example, field_name)))
  File "/root/meshed-memory-transformer-master/data/field.py", line 109, in preprocess
    f = h5py.File(self.detections_path, 'r')
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open

**Comment by baraldilorenzo** [comment]
Hi @bean-point ,

did you specify the right path to the `meshed_memory_transformer.pth` file in the `--features_path` argument? If so, it might be worthwhile to download the features file again and make sure it is not corrupted. Its md5sum should be `695f3eddea88f2f5f7f47febf11e2de2`.

Best,
Lorenzo.
