### ISSUE TITLE
Flag for cpu only evalutaion.

### ISSUE THREAD

**Issue by Akashtyagi08** [aimagelab/meshed-memory-transformer#14]
I tried running the evaluation script "test.py" along with arguments but an error occured as follow 
```
Meshed-Memory Transformer Evaluation
Traceback (most recent call last):
  File "test.py", line 69, in <module>
    model = Transformer(text_field.vocab.stoi['<bos>'], encoder, decoder).to(device)
  File "/home/tarl-group/anaconda3/envs/m2release/lib/python3.6/site-packages/torch/nn/modules/module.py", line 386, in to
    return self._apply(convert)
  File "/home/tarl-group/anaconda3/envs/m2release/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/tarl-group/anaconda3/envs/m2release/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/tarl-group/anaconda3/envs/m2release/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/tarl-group/anaconda3/envs/m2release/lib/python3.6/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/home/tarl-group/anaconda3/envs/m2release/lib/python3.6/site-packages/torch/nn/modules/module.py", line 384, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/tarl-group/anaconda3/envs/m2release/lib/python3.6/site-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    _check_driver()
  File "/home/tarl-group/anaconda3/envs/m2release/lib/python3.6/site-packages/torch/cuda/__init__.py", line 82, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

Looks like the code uses cuda somewhere.
Does the code support cpu only execution ?

**Comment by baraldilorenzo** [comment]
Hi @Akashtyagi08 ,

if you want to run on CPU, you could replace line 42 of `test.py` with
```
device = torch.device('cpu')
```

and line 71 with:
```
data = torch.load('meshed_memory_transformer.pth', map_location=lambda storage, loc: storage)
```

that should do the job. Let me know if it works.

Best,
Lorenzo.

**Comment by Akashtyagi08** [comment]
Thanks @baraldilorenzo  for your input. The changes did seem to work.

But now i am facing the issue as below 

```
Evaluation:   0%|                                                                                                                                               | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test.py", line 78, in <module>
    scores = predict_captions(model, dict_dataloader_test, text_field)
  File "test.py", line 27, in predict_captions
    out, _ = model.beam_search(images, 20, text_field.vocab.stoi['<eos>'], 5, out_size=1)
  File "/home/tarl-group/projects/meshed-memory-transformer/models/captioning_model.py", line 70, in beam_search
    return bs.apply(visual, out_size, return_probs, **kwargs)
  File "/home/tarl-group/projects/meshed-memory-transformer/models/beam_search/beam_search.py", line 71, in apply
    visual, outputs = self.iter(t, visual, outputs, return_probs, **kwargs)
  File "/home/tarl-group/projects/meshed-memory-transformer/models/beam_search/beam_search.py", line 104, in iter
    word_logprob = self.model.step(t, self.selected_words, visual, None, mode='feedback', **kwargs)
  File "/home/tarl-group/projects/meshed-memory-transformer/models/transformer/transformer.py", line 50, in step
    return self.decoder(it, self.enc_output, self.mask_enc)
  File "/home/tarl-group/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/tarl-group/projects/meshed-memory-transformer/models/transformer/decoders.py", line 86, in forward
    self.running_mask_self_attention = torch.cat([self.running_mask_self_attention, mask_self_attention], -1)
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for sequence element 1 in sequence argument at position #1 'tensors'

```
I did look a bit into the issue and it maybe because some function is returning Bool instead of a scaler value, but wasn't able to trace it.

Pytorch version: 1.4.0

**Comment by baraldilorenzo** [comment]
Dear @Akashtyagi08 ,

our code is compatible with Pytorch 1.1.0, only. If you want to use the newest Pytorch version, you can try by casting to bool the mask_self_attention variable. Please let me know if this solves the problem.

Best,
Lorenzo.

**Comment by Akashtyagi08** [comment]
Thanks it worked after switching to 1.0.0 .
