### ISSUE TITLE
Conda Env Create Failed

### ISSUE THREAD

**Issue by Mollylulu** [aimagelab/meshed-memory-transformer#19]
Hi~ when I create the conda env, I got this error 👇 

<img src="https://user-images.githubusercontent.com/26273127/80910134-0c3e2e80-8d60-11ea-9ac4-4cb00b426dfe.png" width="400" height="120">

Could you tell me how to fix it? seems like some channels which used to install these libs not in my conda's config?

**Comment by Jian-Xi** [comment]
Actually you can build the environment via virtualenv. I guess this is a sort of dependency problem. I also tried it previously with Conda and I got some errors but not sure it's the same error here.
Using 
`virtualenv .env_m2m -python python3`
and activate the env_m2m environment by 
`source .env_m2m/bin/activate`
As soon it works, installing all the packages with
 `pip install -r requirement.txt`
Here is the package list  that I exported from my IDE environment in requirement.txt.

`
absl-py==0.8.1
asn1crypto==1.2.0
astroid==2.3.3
attrs==19.3.0
backcall==0.1.0
bleach==3.1.4
blis==0.4.1
catalogue==1.0.0
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
cycler==0.10.0
cymem==2.0.3
Cython==0.29.16
cytoolz==0.9.0.1
decorator==4.4.2
defusedxml==0.6.0
dill==0.2.9
en-core-web-sm==2.2.5
entrypoints==0.3
future==0.17.1
grpcio==1.25.0
h5py==2.8.0
hypothesis==2.0.0
idna==2.8
importlib-metadata==1.6.0
ipykernel==5.2.1
ipython==7.9.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.17.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-core==4.6.3
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==2.2.3
mccabe==0.6.1
mistune==0.8.4
msgpack==0.6.2
msgpack-numpy==0.4.1
msgpack-python==0.5.4
multiprocess==0.70.9
murmurhash==0.28.0
nbconvert==5.6.1
nbformat==5.0.6
notebook==6.0.3
numpy==1.18.3
pandocfilters==1.4.2
parso==0.7.0
pathlib==1.0.1
pathos==0.2.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==6.2.1
plac==0.9.6
pox==0.2.7
ppft==1.6.6.1
preshed==3.0.2
prometheus-client==0.7.1
prompt-toolkit==2.0.10
protobuf==3.10.0
ptyprocess==0.6.0
pycocotools==2.0.0
pycparser==2.19
Pygments==2.6.1
pylint==2.4.4
pyOpenSSL==19.1.0
pyparsing==2.4.5
pyrsistent==0.16.0
PySocks==1.7.1
python-dateutil==2.8.1
pytorch-compact-bilinear-pooling==0.4.0
pytz==2019.3
pyzmq==19.0.0
regex==2017.4.5
requests==2.22.0
Send2Trash==1.5.0
six==1.13.0
spacy==2.2.4
srsly==1.0.2
tensorboard==1.14.0
termcolor==1.1.0
terminado==0.8.3
testpath==0.4.4
thinc==7.4.0
toolz==0.10.0
torch==1.5.0+cu101
torchvision==0.6.0+cu101
tornado==6.0.4
tqdm==4.45.0
traitlets==4.3.3
typed-ast==1.4.1
ujson==1.35
urllib3==1.24.2
wasabi==0.6.0
wcwidth==0.1.9
webencodings==0.5.1
Werkzeug==0.16.0
wrapt==1.10.11
zipp==1.2.0

`

Hopefully it works for you.

**Comment by Mollylulu** [comment]
It does not work for me. 
`
ERROR: No matching distribution found for en-core-web-sm==2.2.5 (from -r requirement.txt (line 20))
`
Then when I comment it out, there still is a issue:
` cwd: /tmp/pip-install-jnufkqh6/pycocotools/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jnufkqh6/pycocotools/setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
:cry:

**Comment by Jian-Xi** [comment]
Please remind that dependency also depends on your system.
If you stay in Ubuntu and Conda, you can just remove the three failed packages including openssl, openmp, mlt.
I tested it with Conda in Ubuntu 18.04  using the environment.yml and succeeded:
`Successfully installed absl-py-0.8.1 cycler-0.10.0 cytoolz-0.9.0.1 dill-0.3.1.1 future-0.17.1 grpcio-1.25.0 h5py-2.8.0 kiwisolver-1.1.0 markdown-3.1.1 matplotlib-2.2.3 msgpack-0.6.2 multiprocess-0.70.9 numpy-1.16.4 pathlib-1.0.1 pathos-0.2.3 pillow-6.2.1 pox-0.2.7 ppft-1.6.6.1 protobuf-3.10.0 pycocotools-2.0.0 pyparsing-2.4.5 python-dateutil-2.8.1 pytz-2019.3 regex-2017.4.5 tensorboard-1.14.0 torch-1.1.0 torchvision-0.3.0 tqdm-4.32.2 ujson-1.35 werkzeug-0.16.0'

To activate this environment, use
'$ conda activate m2release'

'To deactivate an active environment, use'

' $ conda deactivate'

The error you got "en-core-web-sm" comes from spacy possibly.  Again, the packages are environments dependent. If the specific version doesn't work anymore, maybe just comment out the version specification and try to get it works. :D

**Comment by Mollylulu** [comment]
Thanks 👌   @Jian-Xi for your kind reply. After removing these three, it's okay. 
Would these lack three affect further running?

**Comment by SandroJijavadze** [comment]
This is what I made for environment.
Have not tried running training yet, though but environment creation goes successful.

`FROM ubuntu:18.04

RUN apt-get update && apt-get install -y gcc libx11-dev

ADD ./* /tmp/
ADD https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh /tmp
#ADD Anaconda3-2020.02-Linux-x86_64.sh /tmp
RUN cd /tmp && sha256sum --check sha256sum.txt && bash Anaconda3-2020.02-Linux-x86_64.sh -b  && \
    /root/anaconda3/bin/conda env create -f environment.yml && /root/anaconda3/bin/conda init bash

ENV PATH /root/anaconda3/bin:$PATH
CMD ["source", "activate", "m2release"]
`
Inside project directory
├── build
│   ├── sha256sum.txt
│   ├── environment.yml
│   └── Dockerfile

sha256sum.txt file content (verify yourself): 
2b9f088b2022edb474915d9f69a803d6449d5fdb4c303041f60ac4aefcc208bb  Anaconda3-2020.02-Linux-x86_64.sh
